version: "3"

services:
  ftpserver:
    image: "stilliard/pure-ftpd:hardened"
    environment:
      - FTP_USER_NAME=bob
      - FTP_USER_PASS=12345
      - FTP_USER_HOME=/home/bob
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./ftp-content-root:/home/bob/upload"

  sftp:
    image: "atmoz/sftp"
    ports:
    - "22:22"
    volumes:
        - "./ssh-keys/ed25519_key:/etc/ssh/ssh_host_ed25519_key"
        - "./ssh-keys/ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub"
        - "./ssh-keys/rsa_key:/etc/ssh/ssh_host_rsa_key"
        - "./ssh-keys/rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub"
        - "./ftp-content-root:/home/foo/upload"
    command: foo:pass:1001

